### ISSUE TITLE
Error with Anki v23.10 (incl. fix/workaround)

### ISSUE THREAD

**Issue by Heart1010** [glutanimate/reset-card-scheduling#3]
After the v23.10 update the add-on doesn't work anymore.

```
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-07 10:11:33

When loading Reset Card Scheduling:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\300884351\__init__.py", line 15, in <module>
    from . import main
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\300884351\main.py", line 21, in <module>
    from .consts import anki21
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\300884351\consts.py", line 22, in <module>
    addon_path = os.path.dirname(__file__).decode(sys_encoding)
AttributeError: 'str' object has no attribute 'decode'
```
A user mentioned in a review to change the following line

https://github.com/glutanimate/reset-card-scheduling/blob/6f62657ebe1b0683818bff7d55797fdebb3c716d/src/reset_card_scheduling/consts.py#L22

to 

![image](https://github.com/glutanimate/reset-card-scheduling/assets/1481680/661230f5-7fb9-4dc4-abfb-b685f0ac7093)
https://ankiweb.net/shared/info/300884351

_In Python 2, string objects expose a decode() function. In Python 3, however, you don't have to decode your strings they're stored in Unicode._

The new way to check versions - see https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916

![image](https://github.com/glutanimate/reset-card-scheduling/assets/1481680/db07dd80-5116-45e1-9345-4dc94702e1d8)

**Comment by fuchsmd** [comment]
As changing line 22 results in an if-statement with two equal outcomes, I took the liberty of rewriting the `consts.py` and opening a [pull request](https://github.com/glutanimate/reset-card-scheduling/pull/4).

**Comment by william-davies** [comment]
@glutanimate / or anyone with write permissions, could you please merge this PR? I have confirmed the fix works for me as well. I edited consts.py and now the add-on can start-up without the error message. Thank you for this great add-on!
